# Site settings
title: JR-Uno
description: 'JR-Uno - blog personal de inquietudes profesionales'
url: 'http://juagammor.github.io/jekyll-hw/'
baseurl: '/jekyll-hw/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'juagammor'

author:
  name: 'JR Gamez'
  email: juanragamez@gmail.com
  twitter_username: juagammor
  facebook_username: 
  github_username:  juagammor
  linkedin_username:  juagammor

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
